# -*- coding: utf-8 -*-
"""Blender Colab CLI Rendering - V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YFqYI08R0tsqnHa88sMgAWlBiBvmWuxw

# Blender Colab CLI Rendering

## Mount Drive (If in Colab)
"""

try:
  from google.colab import drive
  drive.mount('/content/drive')
except:
  pass

"""## Create directory structure"""

input_dir = '/content'
output_dir = '/content/drive/MyDrive/code/blender/outputs'

!mkdir -p {input_dir}
!mkdir -p {output_dir}

"""## Get Blender Assets"""

import sys
import argparse

# Defaults used by Colab
DEFAULT_BLEND_URL = "https://download.blender.org/demo/cycles/loft.blend"
DEFAULT_BLEND_NAME = "sample.blend"

def get_args():
    # Running inside a notebook/Colab
    if "google.colab" in sys.modules:
        return argparse.Namespace(
            blend_url=DEFAULT_BLEND_URL,
            blend_name=DEFAULT_BLEND_NAME,
            input_dir=input_dir,
            output_dir=output_dir
        )

    # Running as a .py script
    parser = argparse.ArgumentParser()
    parser.add_argument("--blend-url", default=DEFAULT_BLEND_URL, help="URL to download the .blend file from")
    parser.add_argument("--blend-name", default=DEFAULT_BLEND_NAME, help="Filename to save the downloaded .blend file as")
    parser.add_argument("--input-dir", default=input_dir, help="Directory containing input files")
    parser.add_argument("--output-dir", default=output_dir, help="Directory to save outputs to")

    return parser.parse_args()

args = get_args()
blend_name = args.blend_name

!wget {args.blend_url} -O {args.input_dir}/{args.blend_name}

"""## Colab CLI (Custom Toolkit)

### Clone
"""

!git clone https://github.com/LVKinyanjui/Colab-CLI

"""### Prerequisites"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # Make render utils shell scripts executable
# for file in Colab-CLI/render_utils/*.sh; do
#   chmod +x $file
# done
# 
# for file in Colab-CLI/colab_setup//*.sh; do
#   chmod +x $file
# done

"""### Nvidia Toolkit Setup
Available in colab but not on a provisioned VM via SSH
"""

import subprocess

# Simple check for the driver
try:
  subprocess.run(["nvcc", "--version"], check=True)
except:
  exec(open("Colab-CLI/colab_setup/nvidia_tools_fix.py").read())

"""### Install Blender"""

exec(open("Colab-CLI/blender_setup/install_blender.py").read())

# Run in terminal if this doesnt work (exits immediately)
# !python3 Colab-CLI/blender_setup/install_blender.py

# Copy code and use exec on it
# exec(open("Colab-CLI/blender_setup/install_blender.py").read())

"""## Render"""

!./Colab-CLI/render_utils/render_job.sh --frame 1 {input_dir}/{blend_name} {output_dir} &