# -*- coding: utf-8 -*-
"""Blender and Xorg

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P1fa8r6MshVz8OFLrlLoWg124TqNHXe3

## Download and Extraction
"""

# INSTALL NANO (Optional)
#sudo apt update >/dev/null 2>&1 && sudo apt install nano >/dev/null 2>&1

import subprocess
import os

# Helper Command
# Allows quality of life additions to running the command
def run_command(cmd):
  ret = subprocess.run(cmd,
                capture_output=True,
                check = True,   # Allows error checking for non zero exit status
                text=True   # Sets text mode for stdin and stdout, rather than the default bytes
  )
  return ret

version = "blender-5.1.2-linux-x64"
version_file = f"{version}.tar.xz"

# Download
# NEXT STEPS
# Wrap with decorator to ensure future shell commands are executed with the same 'addons'
if not os.path.exists(version_file):
  run_command(["wget", f"https://download.blender.org/release/Blender5.1/{version_file}"])

# Extract
if not os.path.exists(version):
  run_command(['tar', '-xf', version_file])

# Symlinking
import subprocess

# Colab Path Dependency!
run_command(["ln", "-sf", f"/content/{version}/blender", "/usr/local/bin/blender"])

!blender --version

"""## Operations

### Rendering from the CLI

#### Sample Project
"""

sample_name = "mr_elephant.blend"
output_name = "mr_elephant"

# To be appended to end of command
# Since arguments are executed in the order they are specified
custom_args = [
]

# Download
if not os.path.exists(sample_name):
  run_command(["wget", f"https://download.blender.org/demo/eevee/mr_elephant/{sample_name}"])

# frame_no = 1
# cmd = [
#     "blender", "-b", sample_name,
#     "-E", "CYCLES",
#     "-x", "1",
#     "-o", f"//{output_name}",
#     "-f", str(frame_no), "--", # to be replaced with custom args (in order)
#     "--cycles-device", "CUDA+CPU",
# ]
# subprocess.run(cmd, capture_output=True, check=True)

# from concurrent.futures import ThreadPoolExecutor

# with ThreadPoolExecutor(max_workers=3) as executor:
#   for frame_no in range(1, 20):
#     cmd = [
#         "blender", "-b", sample_name,
#         "-E", "CYCLES",
#         "-x", "1",
#         "-o", f"//{output_name}",
#         "-f", str(frame_no), "--", # to be replaced with custom args (in order)
#         "--cycles-device", "CUDA+CPU",
#     ]
#     executor.submit(subprocess.run, cmd, check=True)

"""#### Concurrent Rendering with Tabbed Output Logging

To make it easy to monitor multiple rendering threads without mixing their outputs, we can use `ipywidgets.Tab` and standard outputs (`ipywidgets.Output`) to isolate the console stream for each rendering process.
"""

# import subprocess
# import sys
# from concurrent.futures import ThreadPoolExecutor
# import ipywidgets as widgets
# from IPython.display import display

# def run_blender_thread(frame_no, output_widget):
#     """
#     Runs a Blender instance for a single frame and streams output directly
#     to the designated ipywidgets Output widget.
#     """
#     cmd = [
#         "blender", "-b", sample_name,
#         "-E", "CYCLES",
#         "-x", "1",
#         "-o", f"//{output_name}",
#         "-f", str(frame_no), "--",
#         "--cycles-device", "CUDA"
#     ]

#     with output_widget:
#         print(f"--- Starting render for Frame {frame_no} ---\n")

#     try:
#         # Start the process with redirected stdout and stderr to stream lines
#         process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)

#         # Read output line-by-line in real-time
#         for line in process.stdout:
#             with output_widget:
#                 sys.stdout.write(line)
#                 sys.stdout.flush()

#         process.wait()
#         with output_widget:
#             if process.returncode == 0:
#                 print(f"\n--- Frame {frame_no} completed successfully ---")
#             else:
#                 print(f"\n--- Frame {frame_no} failed with exit code {process.returncode} ---")
#     except Exception as e:
#         with output_widget:
#             print(f"\nError during execution: {e}")

# # Configure frames to render
# frames_to_render = range(1, 4)  # Render frames 1, 2, 3 as a test

# # Create output widgets and tabs for monitoring
# out_widgets = {frame: widgets.Output(layout=widgets.Layout(height='300px', overflow='scroll')) for frame in frames_to_render}
# tab_children = [out_widgets[frame] for frame in frames_to_render]
# tab = widgets.Tab()
# tab.children = tab_children
# for idx, frame in enumerate(frames_to_render):
#     tab.set_title(idx, f"Frame {frame}")

# display(tab)

# # Run the tasks concurrently using ThreadPoolExecutor
# with ThreadPoolExecutor(max_workers=3) as executor:
#     futures = [
#         executor.submit(run_blender_thread, frame, out_widgets[frame])
#         for frame in frames_to_render
#     ]

"""#### Raw Blender command"""

# |# Render
!blender -b mr_elephant.blend -E CYCLES -x 1 -o //render -s 11 -e 15 -t 2 -a -- --cycles-device CUDA+CPU



"""#### Results

**Usage**

- CPU - 4 GB
- GPU - 2 GB

While rendering `mr_elephant.blend`, it consumed a constant `2GB VRAM`

It used `8.6 GB` system RAM. There was, however, an initial process (more details shortly) similar to this one. So this is **twice** the ram usage.

**Note on where to run**
Running the render command with engine set to cycles and specifying CUDA as the engine failed to actually use the GPU when _**run from terminal**_.

##### Next Steps

1. Try rendering on both CPU and GPU
`--cycles-device CUDA+CPU`

2. Changer performance mode to faster to improve rendering speed (we are only using 2 out of the 15GB available)

3. Render simultaneously by launching several render commands concurrently (using `concurrent.futures`)
"""

